/** @type {import('next').NextConfig} */
const nextConfig = {
    images: {
        domains: [
            'i.pinimg.com',
            'c4.wallpaperflare.com',
            'welthi.com',
            'as1.ftcdn.net',
            'media.istockphoto.com',
            'wallpapers.com',
            'img.freepik.com',
            'plus.unsplash.com',
            'static.vecteezy.com',
            'png.pngtree.com',
            'img.bebeautiful.in',
            'www.india.com',
            'i.ytimg.com',
            'res.cloudinary.com',
            'upload.wikimedia.org',
            'images.cnbctv18.com',
            'sika.scene7.com',
            'www.financialexpress.com',
            'img.jagranjosh.com',
            'assets-news.housing.com',
            'website-data-pluckwalk.s3.ap-south-1.amazonaws.com',
            '2.imimg.com',
            'azeuspelletmill.com',
            '5.imimg.com',
            'media-cldnry.s-nbcnews.com',
            'image.chewy.com',
            'www.treehugger.com',
            'www.hosokawa-alpine.com',
            'content.jdmagicbox.com',
            't3.ftcdn.net',
            'www.infinitimall.com',
            'cdn.ecommercedns.uk',
            'simplyfresh.info',
            'maayeka.com',
            'www.farmdidi.com',
            'encrypted-tbn0.gstatic.com',
            'www.eurokidsindia.com',
            'randomuser.me',
            'www.bruker.com',
            'shyamdairy.com',
            'www.krishinutrition.com',
            'img.bebeautiful.in',
            'www.india.com',
            'www.allrecipes.com',
            'm.media-amazon.com',
            'i.ytimg.com',
            'nonprod-media.webdunia.com',
            'www.prakashdairymorbi.com',
            'www.indianhealthyrecipes.com',
            "gdrgroup.in"

        ],
    },
};

export default nextConfig;
